package api

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/brantje/llamacpp-manager/internal/auth"
	"github.com/brantje/llamacpp-manager/internal/downloads"
	"github.com/brantje/llamacpp-manager/internal/hardware"
	"github.com/brantje/llamacpp-manager/internal/lifecycle"
	"github.com/brantje/llamacpp-manager/internal/llamacpp"
	"github.com/brantje/llamacpp-manager/internal/models"
	"github.com/brantje/llamacpp-manager/internal/providers"
	"github.com/brantje/llamacpp-manager/internal/secrets"
)

const sessionCookie="lcm_session"
const hfTokenSecret="huggingface_token"

type Server struct{auth *auth.Service;models *models.Service;lifecycle *lifecycle.Service;hf *providers.HuggingFace;downloads *downloads.Manager;hardware *hardware.Service;secrets *secrets.Store;profile func()(llamacpp.Profile,error)}
func New(authService *auth.Service,modelService *models.Service,lifecycleService *lifecycle.Service,hf *providers.HuggingFace,downloadManager *downloads.Manager,hardwareService *hardware.Service,secretStore *secrets.Store,profile func()(llamacpp.Profile,error))*Server{return &Server{auth:authService,models:modelService,lifecycle:lifecycleService,hf:hf,downloads:downloadManager,hardware:hardwareService,secrets:secretStore,profile:profile}}

func(s *Server)ServeHTTP(w http.ResponseWriter,r *http.Request){path:=strings.TrimSuffix(r.URL.Path,"/");if path==""{path="/"};switch{case path=="/api/v1/health"&&r.Method==http.MethodGet:writeJSON(w,200,map[string]any{"status":"ok"});case path=="/api/v1/auth/bootstrap"&&r.Method==http.MethodGet:required,err:=s.auth.BootstrapRequired(r.Context());if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,map[string]bool{"required":required});case path=="/api/v1/auth/bootstrap"&&r.Method==http.MethodPost:s.bootstrap(w,r);case path=="/api/v1/auth/login"&&r.Method==http.MethodPost:s.login(w,r);case path=="/api/v1/auth/logout"&&r.Method==http.MethodPost:s.logout(w,r);default:user,ok:=s.requireUser(w,r);if !ok{return};if !sameOriginMutation(w,r){return};s.serveAuthenticated(w,r,path,user)}}

func(s *Server)serveAuthenticated(w http.ResponseWriter,r *http.Request,path string,user auth.User){switch{
case path=="/api/v1/me"&&r.Method==http.MethodGet:writeJSON(w,200,user)
case path=="/api/v1/hardware"&&r.Method==http.MethodGet:writeJSON(w,200,s.hardware.Snapshot(r.Context()))
case path=="/api/v1/models":s.modelsRoot(w,r,user)
case path=="/api/v1/artifacts"&&r.Method==http.MethodGet:items,err:=s.models.ListArtifacts(r.Context());if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items)
case path=="/api/v1/artifacts/register"&&r.Method==http.MethodPost:if !requireOperate(w,user){return};var in struct{Path string `json:"path"`;DisplayName string `json:"display_name"`};if !decode(w,r,&in){return};item,err:=s.models.RegisterLocalArtifact(r.Context(),in.Path,in.DisplayName);if err!=nil{writeErr(w,400,err);return};writeJSON(w,201,item)
case path=="/api/v1/llamacpp/profile"&&r.Method==http.MethodGet:profile,err:=s.profile();if err!=nil{writeJSON(w,503,map[string]any{"available":false,"error":err.Error()});return};writeJSON(w,200,map[string]any{"available":true,"profile":profile})
case path=="/api/v1/providers/huggingface/search"&&r.Method==http.MethodGet:items,err:=s.hf.Search(r.Context(),r.URL.Query().Get("q"),30);if err!=nil{writeErr(w,502,err);return};writeJSON(w,200,items)
case strings.HasPrefix(path,"/api/v1/providers/huggingface/models/")&&strings.HasSuffix(path,"/files")&&r.Method==http.MethodGet:repo:=strings.TrimSuffix(strings.TrimPrefix(path,"/api/v1/providers/huggingface/models/"),"/files");items,err:=s.hf.Files(r.Context(),repo);if err!=nil{writeErr(w,502,err);return};writeJSON(w,200,items)
case path=="/api/v1/settings/huggingface":s.huggingFaceSettings(w,r,user)
case path=="/api/v1/downloads"&&r.Method==http.MethodGet:writeJSON(w,200,s.downloads.List())
case path=="/api/v1/downloads/huggingface"&&r.Method==http.MethodPost:if !requireOperate(w,user){return};var in struct{Repo string `json:"repo"`;File string `json:"file"`;Revision string `json:"revision"`};if !decode(w,r,&in){return};job,err:=s.downloads.StartHuggingFace(in.Repo,in.File,in.Revision);if err!=nil{writeErr(w,400,err);return};writeJSON(w,202,job)
case path=="/api/v1/downloads/url"&&r.Method==http.MethodPost:if !requireOperate(w,user){return};var in struct{URL string `json:"url"`};if !decode(w,r,&in){return};job,err:=s.downloads.StartURL(in.URL);if err!=nil{writeErr(w,400,err);return};writeJSON(w,202,job)
case strings.HasPrefix(path,"/api/v1/downloads/")&&strings.HasSuffix(path,"/cancel")&&r.Method==http.MethodPost:if !requireOperate(w,user){return};id:=strings.TrimSuffix(strings.TrimPrefix(path,"/api/v1/downloads/"),"/cancel");if err:=s.downloads.Cancel(id);err!=nil{writeErr(w,404,err);return};w.WriteHeader(204)
case path=="/api/v1/api-keys":s.apiKeysRoot(w,r,user)
case strings.HasPrefix(path,"/api/v1/api-keys/")&&strings.HasSuffix(path,"/revoke")&&r.Method==http.MethodPost:if !auth.IsAdmin(user.Role){writeForbidden(w);return};id:=strings.TrimSuffix(strings.TrimPrefix(path,"/api/v1/api-keys/"),"/revoke");if err:=s.auth.RevokeAPIKey(r.Context(),id);err!=nil{writeErr(w,500,err);return};w.WriteHeader(204)
case path=="/api/v1/users":s.usersRoot(w,r,user)
case strings.HasPrefix(path,"/api/v1/users/"):s.userResource(w,r,path,user)
case strings.HasPrefix(path,"/api/v1/models/"):s.modelResource(w,r,path,user)
case strings.HasPrefix(path,"/api/v1/instances/"):s.instanceResource(w,r,path,user)
default:writeJSON(w,404,map[string]string{"error":"not found"})}}

func(s *Server)modelsRoot(w http.ResponseWriter,r *http.Request,user auth.User){switch r.Method{case http.MethodGet:items,err:=s.models.List(r.Context());if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items);case http.MethodPost:if !requireOperate(w,user){return};var in models.CreateModelInput;if !decode(w,r,&in){return};item,err:=s.models.Create(r.Context(),in);if err!=nil{writeErr(w,400,err);return};writeJSON(w,201,item);default:w.WriteHeader(405)}}
func(s *Server)modelResource(w http.ResponseWriter,r *http.Request,path string,user auth.User){rest:=strings.TrimPrefix(path,"/api/v1/models/");parts:=strings.Split(rest,"/");if len(parts)==0||parts[0]==""{writeJSON(w,404,map[string]string{"error":"not found"});return};id:=parts[0];if len(parts)==1{switch r.Method{case http.MethodGet:item,err:=s.models.GetByID(r.Context(),id);if err!=nil{writeErr(w,404,err);return};writeJSON(w,200,item);case http.MethodPatch:if !requireOperate(w,user){return};var in models.UpdateModelInput;if !decode(w,r,&in){return};item,err:=s.models.Update(r.Context(),id,in);if err!=nil{writeErr(w,400,err);return};writeJSON(w,200,item);case http.MethodDelete:if !auth.IsAdmin(user.Role){writeForbidden(w);return};_ = s.lifecycle.StopModel(r.Context(),id);if err:=s.models.Delete(r.Context(),id);err!=nil{writeErr(w,400,err);return};w.WriteHeader(204);default:w.WriteHeader(405)};return};if len(parts)!=2{writeJSON(w,404,map[string]string{"error":"not found"});return};switch parts[1]{case "start":if r.Method!=http.MethodPost{w.WriteHeader(405);return};if !requireOperate(w,user){return};_,err:=s.lifecycle.StartModel(r.Context(),id);if err!=nil{writeErr(w,503,err);return};runtime,_:=s.lifecycle.RuntimeForModel(r.Context(),id);writeJSON(w,202,runtime);case "stop":if r.Method!=http.MethodPost{w.WriteHeader(405);return};if !requireOperate(w,user){return};if err:=s.lifecycle.StopModel(r.Context(),id);err!=nil{writeErr(w,500,err);return};w.WriteHeader(204);case "runtime":if r.Method!=http.MethodGet{w.WriteHeader(405);return};items,err:=s.lifecycle.RuntimeForModel(r.Context(),id);if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items);case "options":if r.Method==http.MethodGet{items,err:=s.models.Options(r.Context(),id);if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items);return};if r.Method==http.MethodPut{if !requireOperate(w,user){return};var options map[string]string;if !decode(w,r,&options){return};if err:=s.models.ReplaceOptions(r.Context(),id,options);err!=nil{writeErr(w,400,err);return};w.WriteHeader(204);return};w.WriteHeader(405);case "instances":if r.Method==http.MethodGet{items,err:=s.models.Instances(r.Context(),id);if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items);return};if r.Method==http.MethodPost{if !requireOperate(w,user){return};var in models.CreateInstanceInput;if !decode(w,r,&in){return};item,err:=s.models.CreateInstance(r.Context(),id,in);if err!=nil{writeErr(w,400,err);return};writeJSON(w,201,item);return};w.WriteHeader(405);default:writeJSON(w,404,map[string]string{"error":"not found"})}}
func(s *Server)instanceResource(w http.ResponseWriter,r *http.Request,path string,user auth.User){rest:=strings.TrimPrefix(path,"/api/v1/instances/");parts:=strings.Split(rest,"/");if len(parts)==0||parts[0]==""{writeJSON(w,404,map[string]string{"error":"not found"});return};id:=parts[0];if len(parts)==2&&parts[1]=="logs"&&r.Method==http.MethodGet{writeJSON(w,200,map[string]any{"lines":s.lifecycle.Logs(id)});return};if len(parts)!=1{writeJSON(w,404,map[string]string{"error":"not found"});return};switch r.Method{case http.MethodGet:item,err:=s.models.GetInstance(r.Context(),id);if err!=nil{writeErr(w,404,err);return};writeJSON(w,200,item);case http.MethodPatch:if !requireOperate(w,user){return};var in models.CreateInstanceInput;if !decode(w,r,&in){return};item,err:=s.models.UpdateInstance(r.Context(),id,in);if err!=nil{writeErr(w,400,err);return};writeJSON(w,200,item);case http.MethodDelete:if !auth.IsAdmin(user.Role){writeForbidden(w);return};if err:=s.models.DeleteInstance(r.Context(),id);err!=nil{writeErr(w,400,err);return};w.WriteHeader(204);default:w.WriteHeader(405)}}

func(s *Server)apiKeysRoot(w http.ResponseWriter,r *http.Request,user auth.User){if !auth.IsAdmin(user.Role){writeForbidden(w);return};switch r.Method{case http.MethodGet:items,err:=s.auth.ListAPIKeys(r.Context());if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items);case http.MethodPost:var in struct{Name string `json:"name"`};if !decode(w,r,&in){return};key,secret,err:=s.auth.CreateAPIKey(r.Context(),in.Name,user.ID);if err!=nil{writeErr(w,500,err);return};writeJSON(w,201,map[string]any{"key":key,"secret":secret});default:w.WriteHeader(405)}}
func(s *Server)usersRoot(w http.ResponseWriter,r *http.Request,user auth.User){if !auth.IsAdmin(user.Role){writeForbidden(w);return};switch r.Method{case http.MethodGet:items,err:=s.auth.ListUsers(r.Context());if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,items);case http.MethodPost:var in auth.CreateUserInput;if !decode(w,r,&in){return};item,err:=s.auth.CreateUser(r.Context(),in);if err!=nil{writeErr(w,400,err);return};writeJSON(w,201,item);default:w.WriteHeader(405)}}
func(s *Server)userResource(w http.ResponseWriter,r *http.Request,path string,user auth.User){if !auth.IsAdmin(user.Role){writeForbidden(w);return};if r.Method!=http.MethodPatch{w.WriteHeader(405);return};idRaw:=strings.TrimPrefix(path,"/api/v1/users/");id,err:=strconv.ParseInt(idRaw,10,64);if err!=nil{writeErr(w,400,errors.New("invalid user id"));return};var in auth.UpdateUserInput;if !decode(w,r,&in){return};item,err:=s.auth.UpdateUser(r.Context(),id,in);if err!=nil{writeErr(w,400,err);return};writeJSON(w,200,item)}
func(s *Server)huggingFaceSettings(w http.ResponseWriter,r *http.Request,user auth.User){if !auth.IsAdmin(user.Role){writeForbidden(w);return};switch r.Method{case http.MethodGet:configured,err:=s.secrets.Configured(r.Context(),hfTokenSecret);if err!=nil{writeErr(w,500,err);return};writeJSON(w,200,map[string]bool{"configured":configured});case http.MethodPut:var in struct{Token string `json:"token"`};if !decode(w,r,&in){return};if strings.TrimSpace(in.Token)==""{writeErr(w,400,errors.New("token is required"));return};if err:=s.secrets.Set(r.Context(),hfTokenSecret,in.Token);err!=nil{writeErr(w,500,err);return};s.hf.SetToken(in.Token);writeJSON(w,200,map[string]bool{"configured":true});case http.MethodDelete:if err:=s.secrets.Delete(r.Context(),hfTokenSecret);err!=nil{writeErr(w,500,err);return};s.hf.SetToken("");w.WriteHeader(204);default:w.WriteHeader(405)}}

func(s *Server)bootstrap(w http.ResponseWriter,r *http.Request){var in struct{Username string `json:"username"`;Password string `json:"password"`};if !decode(w,r,&in){return};user,err:=s.auth.BootstrapAdmin(r.Context(),in.Username,in.Password);if err!=nil{writeErr(w,400,err);return};writeJSON(w,201,user)}
func(s *Server)login(w http.ResponseWriter,r *http.Request){var in struct{Username string `json:"username"`;Password string `json:"password"`};if !decode(w,r,&in){return};token,user,err:=s.auth.Login(r.Context(),in.Username,in.Password);if err!=nil{writeJSON(w,401,map[string]string{"error":"invalid username or password"});return};http.SetCookie(w,&http.Cookie{Name:sessionCookie,Value:token,Path:"/",HttpOnly:true,Secure:r.TLS!=nil,SameSite:http.SameSiteStrictMode,MaxAge:int((24*time.Hour).Seconds())});writeJSON(w,200,user)}
func(s *Server)logout(w http.ResponseWriter,r *http.Request){if cookie,err:=r.Cookie(sessionCookie);err==nil{_ = s.auth.Logout(r.Context(),cookie.Value)};http.SetCookie(w,&http.Cookie{Name:sessionCookie,Value:"",Path:"/",HttpOnly:true,Secure:r.TLS!=nil,SameSite:http.SameSiteStrictMode,MaxAge:-1});w.WriteHeader(204)}
func(s *Server)requireUser(w http.ResponseWriter,r *http.Request)(auth.User,bool){cookie,err:=r.Cookie(sessionCookie);if err!=nil{writeJSON(w,401,map[string]string{"error":"authentication required"});return auth.User{},false};user,err:=s.auth.SessionUser(r.Context(),cookie.Value);if err!=nil{writeJSON(w,401,map[string]string{"error":"authentication required"});return auth.User{},false};return user,true}
func sameOriginMutation(w http.ResponseWriter,r *http.Request)bool{if r.Method==http.MethodGet||r.Method==http.MethodHead||r.Method==http.MethodOptions{return true};origin:=r.Header.Get("Origin");if origin==""{return true};u,err:=url.Parse(origin);if err!=nil||!strings.EqualFold(u.Host,r.Host){writeJSON(w,403,map[string]string{"error":"cross-origin mutation rejected"});return false};return true}
func requireOperate(w http.ResponseWriter,user auth.User)bool{if !auth.CanOperate(user.Role){writeForbidden(w);return false};return true}
func writeForbidden(w http.ResponseWriter){writeJSON(w,403,map[string]string{"error":"forbidden"})}
func decode(w http.ResponseWriter,r *http.Request,v any)bool{dec:=json.NewDecoder(http.MaxBytesReader(w,r.Body,2<<20));dec.DisallowUnknownFields();if err:=dec.Decode(v);err!=nil{writeErr(w,400,err);return false};return true}
func writeErr(w http.ResponseWriter,status int,err error){if err==nil{err=errors.New("unknown error")};writeJSON(w,status,map[string]string{"error":err.Error()})}
func writeJSON(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(v)}
